module.exports = {
	extends: ["eslint:recommended", "prettier"],
	rules: {
		"no-constructor-return": "error",
		"no-duplicate-imports": "warn",
		"no-new-native-constructors": "error",
		"no-promise-executor-return": "warn",
		"no-self-compare": "warn",
		"no-template-curly-in-string": "warn",
		"no-unmodified-loop-condition": "warn",
		"no-unreachable-loop": "warn",
		"no-unused-private-class-members": "warn",
		"no-use-before-define": "error",
		"require-atomic-updates": "warn",
		// suggestions
		"accessor-pairs": "error",
		"arrow-body-style": ["error", "as-needed"],
		"block-scoped-var": "error",
		camelcase: {
			properties: "always",
		},
		"cyclomatic-complexity": ["error", 10],
		"consistent-return": "error",
		"consistent-this": "error",
		curly: ["error", "all"],
		"default-case": "error",
		"default-case-last": "error",
		"default-param-last": "error",
		"dot-notation": "error",
		eqeqeq: "error",
		"func-name-matching": "error",
		"func-names": "as-needed",
		"func-style": ["error", "declaration", { allowArrowFunctions: true }],
		"grouped-accessor-pairs": "error",
		"init-declarations": ["error", "always"],
		"logical-assignment-operators": ["warn", "always", { enforceForIfStatements: true }],
		"max-classes-per-file": ["error", 1],
		"max-depth": ["warn", 4],
		"max-lines": ["warn", 500],
		"max-lines-per-function": ["warn", 100],
		"max-nested-callbacks": ["warn", 4],
		"max-params": ["warn", 4],
		"multiline-comment-style": ["warn", "starred-block"],
		"new-cap": "error",
		"no-alert": "error",
		"no-array-constructor": "error",
		"no-caller": "error",
		"no-case-declarations": "error",
		"no-confusing-arrow": "warn",
		"no-else-return": "warn",
		"no-empty": "warn",
		"no-empty-function": "warn",
		"no-empty-static-block": "error",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "error",
		"no-extra-label": "warn",
		"no-extra-semi": "error",
		"no-implicit-coercion": ["error", { boolean: false }],
		"no-implied-eval": "error",
		"no-inline-comments": "warn",
		"no-invalid-this": "error",
		"no-iterator": "error",
		"no-label-var": "warn",
		"no-lone-blocks": "warn",
		"no-lonely-if": "warn",
		"no-loop-func": "error",
		"no-magic-numbers": [
			"warn",
			{
				ignore: Array.from({ length: 100 }).map((_, i) => i - 50),
				ignoreArrayIndexes: true,
				ignoreDefaultValues: true,
				detectObjects: true,
				enforceConst: true,
			},
		],
		"no-mixed-operators": "warn",
		"no-negated-condition": "warn",
		"no-nested-ternary": "warn",
		"no-new": "error",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-octal-escape": "error",
		"no-proto": "error",
		"no-return-assign": "error",
		"no-return-await": "error",
		"no-script-url": "error",
		"no-sequences": "error",
		"no-shadow": "error",
		"no-throw-literal": "error",
		"no-undef-init": "error",
		"no-unneeded-ternary": "warn",
		"no-unused-expressions": "warn",
		"no-useless-call": "error",
		"no-useless-computed-key": "warn",
		"no-useless-concat": "warn",
		"no-useless-constructor": "warn",
		"no-useless-rename": "warn",
		"no-useless-return": "warn",
		"no-var": "error",
		"no-void": "error",
		"no-warning-comments": "warn",
		"no-with": "error",
		"object-shorthand": ["warn", "properties"],
		"operator-assignment": ["warn", "always"],
		"prefer-arrow-callback": "error",
		"prefer-const": "warn",
		"prefer-destructuring": [
			"warn",
			{
				array: false,
				object: true,
			},
		],
		"prefer-exponentiation-operator": "warn",
		"prefer-named-capture-group": "warn",
		"prefer-numeric-literals": "warn",
		"prefer-object-has-own": "error",
		"prefer-object-spread": "error",
		"prefer-regex-literals": "error",
		"prefer-rest-params": "error",
		"prefer-spread": "error",
		"prefer-template": "warn",
		"quote-props": ["warn", "as-needed"],
		radix: ["warn", "as-needed"],
		"require-await": "warn",
		"require-unicode-regexp": "warn",
		"spaced-comment": ["warn", "always"],
		yoda: "warn",
		// layout and formatting
		"array-bracket-newline": ["warn", "multiline"],
		"array-bracket-spacing": ["warn", "never"],
		"arrow-parens": ["warn", "always"],
		"arrow-spacing": [
			"warn",
			{
				before: true,
				after: true,
			},
		],
		"block-spacing": ["warn", "always"],
		"brace-style": ["warn", "1tbs"],
		"comma-dangle": ["warn", "only-multiline"],
		"comma-spacing": [
			"warn",
			{
				before: false,
				after: true,
			},
		],
		"comma-style": ["warn", "last"],
		"computed-property-spacing": ["warn", "never"],
		"dot-location": ["warn", "property"],
		"eol-last": ["warn", "always"],
		"func-call-spacing": ["warn", "never"],
		"function-call-argument-newline": ["warn", "consistent"],
		"function-paren-newline": ["warn", "multiline"],
		"generator-star-spacing": [
			"warn",
			{
				before: false,
				after: true,
			},
		],
		"implicit-arrow-linebreak": ["warn", "beside"],
		indent: ["warn", "tab"],
		"jsx-quotes": ["warn", "prefer-double"],
		"key-spacing": [
			"warn",
			{
				beforeColon: false,
				afterColon: true,
			},
		],
		"keyword-spacing": [
			"warn",
			{
				before: true,
				after: true,
			},
		],
		"line-comment-position": ["warn", "above"],
		"linebreak-style": ["warn", "unix"],
		"lines-around-comment": [
			"warn",
			{
				beforeBlockComment: true,
				afterBlockComment: false,
				beforeLineComment: true,
				afterLineComment: false,
				allowBlockStart: true,
				allowBlockEnd: true,
				allowObjectStart: true,
				allowObjectEnd: true,
				allowArrayStart: true,
				allowArrayEnd: true,
				allowClassStart: true,
				allowClassEnd: true,
			},
		],
		"lines-between-class-members": ["warn", "always", { exceptAfterSingleLine: true }],
		"max-len": [
			"warn",
			{
				code: 100,
				tabWidth: 4,
			},
		],
		"max-statements-per-line": ["warn", { max: 1 }],
		"new-parens": "warn",
		"newline-per-chained-call": ["warn", { ignoreChainWithDepth: 2 }],
		"no-extra-parens": [
			"warn",
			{
				nestedBinaryExpressions: false,
			},
		],
		"no-multi-spaces": "warn",
		"no-multiple-empty-lines": [
			"warn",
			{
				max: 1,
				maxEOF: 1,
			},
		],
		"no-trailing-spaces": "warn",
		"no-whitespace-before-property": "warn",
		"object-curly-newline": [
			"warn",
			{
				multiline: true,
			},
		],
		"object-curly-spacing": ["warn", "always"],
		"object-property-newline": ["warn", "always"],
		"operator-linebreak": ["warn", "before"],
		"padded-blocks": ["warn", "never"],
		"padding-line-between-statements": [
			{ blankLine: "always", prev: ["const", "let", "var"], next: "*" },
			{ blankLine: "any", prev: ["const", "let", "var"], next: ["const", "let", "var"] },
		],
		quotes: ["warn", "double"],
		"rest-spread-spacing": ["warn", "never"],
		semi: ["warn", "always"],
		"semi-spacing": [
			"warn",
			{
				before: false,
				after: true,
			},
		],
		"semi-style": ["warn", "last"],
		"space-before-blocks": ["warn", "always"],
		"space-before-function-paren": [
			"warn",
			{
				anonymous: "always",
				named: "never",
				asyncArrow: "always",
			},
		],
		"space-in-parens": ["warn", "never"],
		"space-infix-ops": "warn",
		"space-unary-ops": [
			"warn",
			{
				words: true,
				nonwords: false,
			},
		],
		"switch-colon-spacing": [
			"warn",
			{
				after: true,
				before: false,
			},
		],
		"template-curly-spacing": ["warn", "never"],
		"template-tag-spacing": ["warn", "never"],
		"unicode-bom": ["warn", "never"],
		"wrap-iife": ["warn", "inside"],
		"wrap-regex": ["warn", "before"],
	},
};
